project:
  type: book
  output-dir: docs

book:
  favicon: data/images/rl-logo.png
  sidebar:
    title: false
    logo: data/images/rl-logo.png
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Lecture 1: Introduction"
      chapters:
        - text: "1.1 Why should I study Reinforcement Learning?"
          file: lecture1/lecture1-1.qmd
        - text: "1.2 What is Reinforcement Learning?"
          file: lecture1/lecture1-2.qmd
        - text: "1.3 Where is Reinforcement Learning Applied?"
          file: lecture1/lecture1-3.qmd
        - text: "1.4 How is Reinforcement Learning Structured?"
          file: lecture1/lecture1-4.qmd
    - part: "Lecture 2: Mathematical Foundations"
      chapters:
        - text: "2.1 Set Theory"
          file: lecture2/lecture2-1.qmd
        - text: "2.2 Axiomatic Probability"
          file: lecture2/lecture2-2.qmd
        - text: "2.3 Conditioning"
          file: lecture2/lecture2-3.qmd
        - text: "2.4 Independence"
          file: lecture2/lecture2-4.qmd
        - text: "2.5 Discrete Random Variables"
          file: lecture2/lecture2-5.qmd
        - text: "2.6 Continuous Random Variables"
          file: lecture2/lecture2-6.qmd
        # - text: "2.7 Probability Distributions"
          # file: lecture2/lecture2-7.qmd
    - part: "Homeworks"
      chapters:
        - text: "Homework 1"
          file: homework/homework1.qmd
    - references.qmd
    # - part: "Lecture 3: Multi-Armed Bandits"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd
    # - part: "Lecture 4: Dynamic Programming"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd
    # - part: "Lecture 5: Monte Carlo"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd
    # - part: "Lecture 6: Temporal Differencing"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd
    # - part: "Lecture 7: Function Approximation"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd  
    # - part: "Lecture 8: Deep Q-Networks"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd 
    # - part: "Lecture 9: Policy Gradients"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd    
    # - part: "Lecture 10: Advanced Policy Gradients"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd   
    # - part: "Lecture 11: Monte Carlo Tree Search"
    #   chapters:
    #     - text: "2.1 Introduction to ML"
    #       file: index.qmd
    #     - text: "2.2 Neural Networks"
    #       file: index.qmd

bibliography: references.bib

format:
  html:
    bread-crumbs: false
    number-sections: false
    grid:
      body-width: 1000px
      sidebar-width: 320px
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



